
USE MASTER
GO

CREATE DATABASE SERRTodo
GO

USE SERRTodo
GO

CREATE TABLE Users
(
	UserID INT IDENTITY(1,1) PRIMARY KEY,
	FullName VARCHAR(200)
)
GO

CREATE TABLE TodoType
(
	TodoTypeID INT IDENTITY(1,1) PRIMARY KEY,
	TodoTypeName VARCHAR(100) NOT NULL DEFAULT('')
)
GO

CREATE TABLE Todo
(
	TodoID INT IDENTITY(1,1) PRIMARY KEY,
	UserID INT NOT NULL DEFAULT(0),
	TodoTypeID INT NOT NULL DEFAULT(0),
	DueDate DATETIME NOT NULL,
	Comment VARCHAR(250) NOT NULL DEFAULT(''),
	DateFlag DATETIME NOT NULL DEFAULT(GETDATE()),
	IsActive BIT NOT NULL DEFAULT(1)
)
GO